## CRUD [/users]

### Search [GET]

*Get paginated list of items.*

Available includes: **[favoriteMovies, wishlistMovies, comments]**

Available parameters <a href="#header-filters">See more...</a>

+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: Ok (string)
        + data (array[User])
<!-- include(responses/pagination.apib) -->

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

### Store [POST]

*Store a newly created item in database.*

Available includes: [favoriteMovies, wishlistMovies, comments]

**Request rules**

```
email: 'required|max:255'
password: 'required'

```

+ Request (application/json)
    <!-- include(requests/header.apib) -->
    + Attributes
        + email: `'str'` (string)
        + password: `'str'` (string)


+ Response 201 (application/json)
    + Attributes
        + message: User has been successfully created (string)
        + data (User)

<!-- include(responses/401.apib) -->
<!-- include(responses/422.apib) -->
<!-- include(responses/500.apib) -->

### Update [PUT /{id}]

*Update the specified item in database.*

Available includes: **[favoriteMovies, wishlistMovies, comments]**


	        'name' => 'required',
	        'avatar' => 'nullable|image',


<!-- include(parameters/id.apib) -->
+ Request (application/json)
    <!-- include(requests/header.apib) -->
    + Attributes
        + email: `'str'` (string)
        + password: `'str'` (string)

+ Response 200 (application/json)
    + Attributes
        + message: User has been successfully updated (string)
        + data (User)

<!-- include(responses/401.apib) -->
<!-- include(responses/404.apib) -->
<!-- include(responses/422.apib) -->
<!-- include(responses/500.apib) -->

### Show [GET /{id}]

*Display the specified item.*

Available includes: **[user]**

<!-- include(parameters/id.apib) -->
+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: null (string)
        + data (User)

<!-- include(responses/401.apib) -->
<!-- include(responses/404.apib) -->
<!-- include(responses/500.apib) -->

### Delete [DELETE /{id}]

*Remove the specified item from storage.*

<!-- include(parameters/id.apib) -->
+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: User has been successfully deleted (string)
        + data : null (string, nullable)

<!-- include(responses/401.apib) -->
<!-- include(responses/404.apib) -->
<!-- include(responses/500.apib) -->

### Bulk store [POST /bulk]

*Bulk store multiple resources.*

Available includes: **[favoriteMovies, wishlistMovies, comments]**

**Request rules**

```
email: 'required|max:255'
password: 'required'

```

+ Request (application/json)
    <!-- include(requests/header.apib) -->
    + Body
```
    [
            {
                "email": `'str'` (string)
                "password": `'str'` (string)

            },
            {
                "email": `'str'` (string)
                "password": `'str'` (string)

            },
    ]
```

+ Response 201 (application/json)
    + Attributes
        + message: Group of Users successfully created (string)
        + data : null (string, nullable)

<!-- include(responses/401.apib) -->
<!-- include(responses/422.apib) -->
<!-- include(responses/500.apib) -->

### Bulk delete [DELETE /bulk]

*Bulk delete multiple resources.*

+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: Group of Users successfully deleted (string)
        + data : null (string, nullable)

<!-- include(responses/401.apib) -->
<!-- include(responses/404.apib) -->
<!-- include(responses/500.apib) -->

##  FavoriteMovies [/users/favorite-movies]

### Search [GET]

Available includes: **[actors, directors, favoritedUsers, wishlistedUsers]**

Available parameters <a href="#header-filters">See more...</a>


+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: null (string)
        + data (array[Movie])
<!-- include(responses/pagination.apib) -->

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

### Attach [POST /favorite-movies/{movie}]

**Request rules**

```
note: 'nullable'
rate: 'nullable|integer|min:0'

```

+ Parameters

    + movie: 1 (number)

+ Request (application/json)
    <!-- include(requests/header.apib) -->
    + Attributes
        + note: `'text'` (string)
        + rate: `'64'` (number)


+ Response 201 (application/json)
    + Attributes
        + message: Movie has been successfully added to list (string)
        + data (User)

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

### Detach [DELETE /favorite-movies/{movie}]

+ Parameters

    + movie: 1 (number)

+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: Movie has been successfully removed from list (string)
        + data : null (string, nullable)

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

##  WishlistMovies [/users/wishlist-movies]

### Search [GET]

Available includes: **[actors, directors, favoritedUsers, wishlistedUsers]**

Available parameters <a href="#header-filters">See more...</a>


+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: null (string)
        + data (array[Movie])
<!-- include(responses/pagination.apib) -->

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

### Attach [POST /wishlist-movies/{movie}]

**Request rules**

```
note: 'nullable'

```

+ Parameters

    + movie: 1 (number)

+ Request (application/json)
    <!-- include(requests/header.apib) -->
    + Attributes
        + note: `'text'` (string)


+ Response 201 (application/json)
    + Attributes
        + message: Movie has been successfully added to list (string)
        + data (User)

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

### Detach [DELETE /wishlist-movies/{movie}]

+ Parameters

    + movie: 1 (number)

+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: Movie has been successfully removed from list (string)
        + data : null (string, nullable)

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->

##  Comments [/users/comments]

### Search [GET]

Available includes: **[creator]**

Available parameters <a href="#header-filters">See more...</a>


+ Request (application/json)
    <!-- include(requests/header.apib) -->
+ Response 200 (application/json)
    + Attributes
        + message: null (string)
        + data (array[Comment])
<!-- include(responses/pagination.apib) -->

<!-- include(responses/401.apib) -->
<!-- include(responses/500.apib) -->




